export const ads = [
  {
    id: 1,
    title: "Наушники",
    price: 2990,
    category: "Электроника",
    requiresRevision: false,
  },
  {
    id: 2,
    title: "Volkswagen Polo",
    price: 1100000,
    category: "Авто",
    requiresRevision: true,
  },
  {
    id: 3,
    title: "Студия, 25м²",
    price: 15000000,
    category: "Недвижимость",
    requiresRevision: false,
  },
  {
    id: 4,
    title: "1-кк, 44м²",
    price: 19000000,
    category: "Недвижимость",
    requiresRevision: true,
  },
  {
    id: 5,
    title: "Наушники",
    price: 2990,
    category: "Электроника",
    requiresRevision: false,
  },
  {
    id: 6,
    title: "Volkswagen Polo",
    price: 1100000,
    category: "Авто",
    requiresRevision: true,
  },
  {
    id: 7,
    title: "Студия, 25м²",
    price: 15000000,
    category: "Недвижимость",
    requiresRevision: false,
  },
  {
    id: 8,
    title: "1-кк, 44м²",
    price: 19000000,
    category: "Недвижимость",
    requiresRevision: true,
  },
  {
    id: 9,
    title: "Наушники",
    price: 2990,
    category: "Электроника",
    requiresRevision: false,
  },
  {
    id: 10,
    title: "Volkswagen Polo",
    price: 1100000,
    category: "Авто",
    requiresRevision: true,
  },
  {
    id: 11,
    title: "Студия, 25м²",
    price: 15000000,
    category: "Недвижимость",
    requiresRevision: false,
  },
  {
    id: 12,
    title: "1-кк, 44м²",
    price: 19000000,
    category: "Недвижимость",
    requiresRevision: true,
  },
];
